#!/usr/bin/env bash
# Ping an IP address passed as an argument, 5 times

if [ $# -lt 1 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$1"


#cd ~/holberton/holbertonschool-network/basics_0
#sed -i 's/\r$//' 5-is_the_host_on_the_network
#head -2 5-is_the_host_on_the_network
#chmod +x 5-is_the_host_on_the_network
#./5-is_the_host_on_the_network 8.8.8.8
