#!/usr/bin/env bash
#!/bin/bash
# This script modifies /etc/hosts to change localhost and facebook.com IP addresses
sudo sed -i '/127.0.0.2 localhost/d' /etc/hosts
sudo sed -i '/8.8.8.8 facebook.com/d' /etc/hosts